### ISSUE TITLE
Issue running function-sample-aws project

### ISSUE THREAD

**Issue by maaraoffl** [laxika/spring-cloud-function-aws-example#2]
Hi - I am getting below exception when i make the REST call. Please advise.

```
curl -H "Content-Type: text/plain" localhost:8080/uppercase -d Hello
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

```
java -jar function-sample-aws-1.0.0.BUILD-SNAPSHOT.jar
Exception in thread "main" java.lang.IllegalStateException: Cannot locate library: /Users/amg871/.m2/repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.7.RELEASE/spring-boot-thin-launcher-1.0.7.RELEASE-exec.jar
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:113)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:90)
```

**Comment by laxika** [comment]
Are you trying to run the built jar locally? To be honest I never tried that before. It should work but I think you will need to tweak the config a little bit. If you come up with a solution I'm more than happy to add it to the code. :)
